/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.statsig.jsonc --include-runtime=false --env-interface=StatsigEnv worker-statsig-configuration.d.ts` (hash: 0b01053997a21b7fd8480b650e96054a)
interface __BaseEnv_StatsigEnv {
	APP_ID: "reference-app";
	APP_ENVIRONMENT: "staging" | "production";
	TENANT_ID: "reference-tenant";
	EVALUATOR_VERSION: "staging" | "local";
	CONFIG_SPECS_TTL_SECONDS: "60" | "300";
	DECISIONS_TTL_SECONDS: "30" | "60";
	DECISIONS_STALE_SECONDS: "60" | "300";
	STATSIG_SERVER_SECRET: string;
	USER_CACHE_HMAC_SECRET: string;
	INVALIDATION_SECRET: string;
	CONFIG_SPECS_CACHE: any;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/statsig/index");
	}
	interface StagingEnv {
		APP_ID: "reference-app";
		APP_ENVIRONMENT: "staging";
		TENANT_ID: "reference-tenant";
		EVALUATOR_VERSION: "staging";
		CONFIG_SPECS_TTL_SECONDS: "60";
		DECISIONS_TTL_SECONDS: "30";
		DECISIONS_STALE_SECONDS: "60";
		STATSIG_SERVER_SECRET: string;
		USER_CACHE_HMAC_SECRET: string;
		INVALIDATION_SECRET: string;
		CONFIG_SPECS_CACHE: any;
	}
	interface Env extends __BaseEnv_StatsigEnv {}
}
interface StatsigEnv extends __BaseEnv_StatsigEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ID" | "APP_ENVIRONMENT" | "TENANT_ID" | "EVALUATOR_VERSION" | "CONFIG_SPECS_TTL_SECONDS" | "DECISIONS_TTL_SECONDS" | "DECISIONS_STALE_SECONDS" | "STATSIG_SERVER_SECRET" | "USER_CACHE_HMAC_SECRET" | "INVALIDATION_SECRET">> {}
}
