/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b75183fe6fad175b4790fba9cf442542)
interface __BaseEnv_Env {
	APP_ID: "reference-app";
	APP_ENVIRONMENT: "production";
	APP_VERSION: "local";
	AUTH_TRUST_HOST: "true";
	DEMO_PASSWORD_DISPLAY: "demo-password";
	AUTH_SECRET: string;
	DEMO_USERNAME: string;
	DEMO_PASSWORD_HASH: string;
	FEATURE_SERVICE: Service /* entrypoint FeatureGatewayEntrypoint from reference-example-kitchen-sink-statsig */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/app/server");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ID" | "APP_ENVIRONMENT" | "APP_VERSION" | "AUTH_TRUST_HOST" | "DEMO_PASSWORD_DISPLAY" | "AUTH_SECRET" | "DEMO_USERNAME" | "DEMO_PASSWORD_HASH">> {}
}
